version: "3.2"

services:
  #Database
 db:
  image: postgres
  container_name: postgres
  restart: always
  environment:
    POSTGRES_PASSWORD: postgres
  networks:
   - backend
  # volumes:
  #  - ./db:/var/lib/postgresql/data
  ports:
   - "5432:5432"

  #Database manager
 adminer:
  image: adminer
  container_name: adminer
  restart: always
  networks:
   - backend
  ports:
   - 8080:8080
  depends_on:
   - db

networks:
 backend:
  driver: bridge
