# GET http://10.12.8.15:3000/user

##POST http://10.12.8.15:3000/user

POST http://10.12.8.15:3000/user/me
Content-Type: application/json

{
    "token":"44de22e392ccddce7f5090df071789fd0472dc4b42b876b525d82f3e02ef175b"
}


###
POST http://10.12.8.15:3000/user
Content-Type: application/json


{
    "name": "kid-bouh",
    "email": "kid-bouh@student.1337.ma",
    "token": "44de22e392ccddce7f5090df071789fd0472dc4b42b876b525d82f3e02ef175b",
    "created_at": "2022-02-27T20:48:07.487Z",
    "updated_at": "2022-02-27T20:48:07.487Z",
    "deleted_at": "2022-02-27T20:48:07.487Z",
    "is_online": true,
    "image": "https://cdn.intra.42.fr/users/kid-bouh.jpg",
    "is_verified": true
}


###
GET http://10.12.8.15:3000/user/random

###
POST  http://10.12.8.15:3000/game/invite
Content-Type: application/json

{
    "username1": "zdnaya",
    "username2": "helkhatr"
}

###
GET http://10.12.8.15:3000/game/is_invited/10

###
GET http://10.12.8.15:3000/game/current/

###
GET http://10.12.8.15:3000/game/is_waiting/10

###

GET http://10.12.8.15:3000/game/finish/88/10

###

GET  http://10.12.8.15:3000/game/watch/219

###
GET http://10.12.8.15:3000/game/is_invited/10

###

GET http://10.12.8.15:3000/game/invited/confirm/10/245