FROM node:16
WORKDIR /app/webapp/front-end
COPY ./front-end/  .
# RUN npm install && npm build && npm start
# WORKDIR /app/webapp/server
# COPY ./server/ ./server
# RUN npm install
# EXPOSE 3001
# EXPOSE 3000
# CMD ["npm", "run", "start:dev"]

CMD ["tail", "-f"]
