version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - web
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - web
  frontdend:
    build: 
         context: ./front-end/
    container_name: front_end
    environment:
      DB_UPSTREAM: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:host-gateway
    image: front_end
    depends_on:
      - backdend
    restart: always
    ports:
        - "3000:3000"
    networks:
      - web
  backdend:
    build:
         context: ./server/
    container_name: back_end
    image: back_end
    restart: always
    depends_on:
      - db
    ports:
        - "3001:3001"
        - "3080:3080"
    networks:
      - web
networks:
  web:
    driver: bridge